// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/logs/v1/logs_service.proto

// Protobuf Java Version: 4.26.1
package io.opentelemetry.proto.collector.logs.v1;

/**
 * Protobuf type {@code opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse}
 */
public final class ExportLogsServiceResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)
    ExportLogsServiceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ExportLogsServiceResponse.class.getName());
  }
  // Use ExportLogsServiceResponse.newBuilder() to construct.
  private ExportLogsServiceResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExportLogsServiceResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.class, io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PARTIAL_SUCCESS_FIELD_NUMBER = 1;
  private io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partialSuccess_;
  /**
   * <pre>
   * The details of a partially successful export request.
   *
   * If the request is only partially accepted
   * (i.e. when the server accepts only parts of the data and rejects the rest)
   * the server MUST initialize the `partial_success` field and MUST
   * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
   *
   * Servers MAY also make use of the `partial_success` field to convey
   * warnings/suggestions to senders even when the request was fully accepted.
   * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
   * the `error_message` MUST be non-empty.
   *
   * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
   * `error_message` = "") is equivalent to it not being set/present. Senders
   * SHOULD interpret it the same way as in the full success case.
   * </pre>
   *
   * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
   * @return Whether the partialSuccess field is set.
   */
  @java.lang.Override
  public boolean hasPartialSuccess() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The details of a partially successful export request.
   *
   * If the request is only partially accepted
   * (i.e. when the server accepts only parts of the data and rejects the rest)
   * the server MUST initialize the `partial_success` field and MUST
   * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
   *
   * Servers MAY also make use of the `partial_success` field to convey
   * warnings/suggestions to senders even when the request was fully accepted.
   * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
   * the `error_message` MUST be non-empty.
   *
   * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
   * `error_message` = "") is equivalent to it not being set/present. Senders
   * SHOULD interpret it the same way as in the full success case.
   * </pre>
   *
   * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
   * @return The partialSuccess.
   */
  @java.lang.Override
  public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess getPartialSuccess() {
    return partialSuccess_ == null ? io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance() : partialSuccess_;
  }
  /**
   * <pre>
   * The details of a partially successful export request.
   *
   * If the request is only partially accepted
   * (i.e. when the server accepts only parts of the data and rejects the rest)
   * the server MUST initialize the `partial_success` field and MUST
   * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
   *
   * Servers MAY also make use of the `partial_success` field to convey
   * warnings/suggestions to senders even when the request was fully accepted.
   * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
   * the `error_message` MUST be non-empty.
   *
   * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
   * `error_message` = "") is equivalent to it not being set/present. Senders
   * SHOULD interpret it the same way as in the full success case.
   * </pre>
   *
   * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessOrBuilder getPartialSuccessOrBuilder() {
    return partialSuccess_ == null ? io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance() : partialSuccess_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPartialSuccess());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPartialSuccess());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)) {
      return super.equals(obj);
    }
    io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse other = (io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse) obj;

    if (hasPartialSuccess() != other.hasPartialSuccess()) return false;
    if (hasPartialSuccess()) {
      if (!getPartialSuccess()
          .equals(other.getPartialSuccess())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPartialSuccess()) {
      hash = (37 * hash) + PARTIAL_SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + getPartialSuccess().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)
      io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.class, io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.Builder.class);
    }

    // Construct using io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getPartialSuccessFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      partialSuccess_ = null;
      if (partialSuccessBuilder_ != null) {
        partialSuccessBuilder_.dispose();
        partialSuccessBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_descriptor;
    }

    @java.lang.Override
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse getDefaultInstanceForType() {
      return io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse build() {
      io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse buildPartial() {
      io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse result = new io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.partialSuccess_ = partialSuccessBuilder_ == null
            ? partialSuccess_
            : partialSuccessBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse) {
        return mergeFrom((io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse other) {
      if (other == io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.getDefaultInstance()) return this;
      if (other.hasPartialSuccess()) {
        mergePartialSuccess(other.getPartialSuccess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPartialSuccessFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partialSuccess_;
    private com.google.protobuf.SingleFieldBuilder<
        io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessOrBuilder> partialSuccessBuilder_;
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     * @return Whether the partialSuccess field is set.
     */
    public boolean hasPartialSuccess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     * @return The partialSuccess.
     */
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess getPartialSuccess() {
      if (partialSuccessBuilder_ == null) {
        return partialSuccess_ == null ? io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance() : partialSuccess_;
      } else {
        return partialSuccessBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    public Builder setPartialSuccess(io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess value) {
      if (partialSuccessBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        partialSuccess_ = value;
      } else {
        partialSuccessBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    public Builder setPartialSuccess(
        io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder builderForValue) {
      if (partialSuccessBuilder_ == null) {
        partialSuccess_ = builderForValue.build();
      } else {
        partialSuccessBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    public Builder mergePartialSuccess(io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess value) {
      if (partialSuccessBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          partialSuccess_ != null &&
          partialSuccess_ != io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance()) {
          getPartialSuccessBuilder().mergeFrom(value);
        } else {
          partialSuccess_ = value;
        }
      } else {
        partialSuccessBuilder_.mergeFrom(value);
      }
      if (partialSuccess_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    public Builder clearPartialSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      partialSuccess_ = null;
      if (partialSuccessBuilder_ != null) {
        partialSuccessBuilder_.dispose();
        partialSuccessBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder getPartialSuccessBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPartialSuccessFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessOrBuilder getPartialSuccessOrBuilder() {
      if (partialSuccessBuilder_ != null) {
        return partialSuccessBuilder_.getMessageOrBuilder();
      } else {
        return partialSuccess_ == null ?
            io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance() : partialSuccess_;
      }
    }
    /**
     * <pre>
     * The details of a partially successful export request.
     *
     * If the request is only partially accepted
     * (i.e. when the server accepts only parts of the data and rejects the rest)
     * the server MUST initialize the `partial_success` field and MUST
     * set the `rejected_&lt;signal&gt;` with the number of items it rejected.
     *
     * Servers MAY also make use of the `partial_success` field to convey
     * warnings/suggestions to senders even when the request was fully accepted.
     * In such cases, the `rejected_&lt;signal&gt;` MUST have a value of `0` and
     * the `error_message` MUST be non-empty.
     *
     * A `partial_success` message with an empty value (rejected_&lt;signal&gt; = 0 and
     * `error_message` = "") is equivalent to it not being set/present. Senders
     * SHOULD interpret it the same way as in the full success case.
     * </pre>
     *
     * <code>.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess partial_success = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessOrBuilder> 
        getPartialSuccessFieldBuilder() {
      if (partialSuccessBuilder_ == null) {
        partialSuccessBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessOrBuilder>(
                getPartialSuccess(),
                getParentForChildren(),
                isClean());
        partialSuccess_ = null;
      }
      return partialSuccessBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse)
  private static final io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse();
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportLogsServiceResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExportLogsServiceResponse>() {
    @java.lang.Override
    public ExportLogsServiceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExportLogsServiceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExportLogsServiceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

