// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/logs/v1/logs_service.proto

// Protobuf Java Version: 4.26.1
package io.opentelemetry.proto.collector.logs.v1;

/**
 * Protobuf type {@code opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess}
 */
public final class ExportLogsPartialSuccess extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess)
    ExportLogsPartialSuccessOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ExportLogsPartialSuccess.class.getName());
  }
  // Use ExportLogsPartialSuccess.newBuilder() to construct.
  private ExportLogsPartialSuccess(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExportLogsPartialSuccess() {
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.class, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder.class);
  }

  public static final int REJECTED_LOG_RECORDS_FIELD_NUMBER = 1;
  private long rejectedLogRecords_ = 0L;
  /**
   * <pre>
   * The number of rejected log records.
   *
   * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
   * request was fully accepted.
   * </pre>
   *
   * <code>int64 rejected_log_records = 1;</code>
   * @return The rejectedLogRecords.
   */
  @java.lang.Override
  public long getRejectedLogRecords() {
    return rejectedLogRecords_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * A developer-facing human-readable message in English. It should be used
   * either to explain why the server rejected parts of the data during a partial
   * success or to convey warnings/suggestions during a full success. The message
   * should offer guidance on how users can address such issues.
   *
   * error_message is an optional field. An error_message with an empty value
   * is equivalent to it not being set.
   * </pre>
   *
   * <code>string error_message = 2;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A developer-facing human-readable message in English. It should be used
   * either to explain why the server rejected parts of the data during a partial
   * success or to convey warnings/suggestions during a full success. The message
   * should offer guidance on how users can address such issues.
   *
   * error_message is an optional field. An error_message with an empty value
   * is equivalent to it not being set.
   * </pre>
   *
   * <code>string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rejectedLogRecords_ != 0L) {
      output.writeInt64(1, rejectedLogRecords_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, errorMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rejectedLogRecords_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, rejectedLogRecords_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, errorMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess)) {
      return super.equals(obj);
    }
    io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess other = (io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess) obj;

    if (getRejectedLogRecords()
        != other.getRejectedLogRecords()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REJECTED_LOG_RECORDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRejectedLogRecords());
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess)
      io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.class, io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.Builder.class);
    }

    // Construct using io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rejectedLogRecords_ = 0L;
      errorMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentelemetry.proto.collector.logs.v1.LogsServiceProto.internal_static_opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_descriptor;
    }

    @java.lang.Override
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess getDefaultInstanceForType() {
      return io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess build() {
      io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess buildPartial() {
      io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess result = new io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rejectedLogRecords_ = rejectedLogRecords_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess) {
        return mergeFrom((io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess other) {
      if (other == io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.getDefaultInstance()) return this;
      if (other.getRejectedLogRecords() != 0L) {
        setRejectedLogRecords(other.getRejectedLogRecords());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              rejectedLogRecords_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long rejectedLogRecords_ ;
    /**
     * <pre>
     * The number of rejected log records.
     *
     * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
     * request was fully accepted.
     * </pre>
     *
     * <code>int64 rejected_log_records = 1;</code>
     * @return The rejectedLogRecords.
     */
    @java.lang.Override
    public long getRejectedLogRecords() {
      return rejectedLogRecords_;
    }
    /**
     * <pre>
     * The number of rejected log records.
     *
     * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
     * request was fully accepted.
     * </pre>
     *
     * <code>int64 rejected_log_records = 1;</code>
     * @param value The rejectedLogRecords to set.
     * @return This builder for chaining.
     */
    public Builder setRejectedLogRecords(long value) {

      rejectedLogRecords_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of rejected log records.
     *
     * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
     * request was fully accepted.
     * </pre>
     *
     * <code>int64 rejected_log_records = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRejectedLogRecords() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rejectedLogRecords_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     *
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     *
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     *
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     *
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     *
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess)
  private static final io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess();
  }

  public static io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportLogsPartialSuccess>
      PARSER = new com.google.protobuf.AbstractParser<ExportLogsPartialSuccess>() {
    @java.lang.Override
    public ExportLogsPartialSuccess parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExportLogsPartialSuccess> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExportLogsPartialSuccess> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

