
version: "3.5"
services:


###################################
### OTEL COLLECTOR
###################################
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    
    container_name: otel-collector
    command: "--config=/etc/otel-collector-config.yaml ${OTELCOL_ARGS}"
    # Change the "source" path below to swap out collector config files!
    volumes:
      - type: bind
        source: ./otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector 
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
      - "55681:55681" # http
    environment:
      # uses .env file
      X_API_KEY: "xxxx"
    depends_on:
      - jaeger

###################################
### OTEL COLLECTOR
###################################
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"

